#!/usr/bin/env python3
"""Generate conf/profiles/<name>.local.yaml from the live terraform outputs.

The committed profiles deliberately carry no addresses: `endpoint`, `tsg_host`
and `minio_ping_host` change on every `tf-apply`, and a profile that stores
them is one `git add` away from publishing a deploy's private topology. This
reads them from terraform instead and writes a generated sibling that
.gitignore excludes, so the run targets always match the running testbed.

    python scripts/configure_profile.py [--profile conf/profiles/experiment.yaml]
"""
import argparse
import json
import subprocess
import sys
from pathlib import Path

TF_DIR = Path(__file__).resolve().parent.parent / "terraform"


def terraform_outputs() -> dict:
    out = subprocess.run(["terraform", f"-chdir={TF_DIR}", "output", "-json"],
                         capture_output=True, text=True)
    if out.returncode != 0:
        sys.exit(f"terraform output failed — is the testbed applied?\n{out.stderr.strip()}")
    return {k: v["value"] for k, v in json.loads(out.stdout).items()}


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--profile", default="conf/profiles/experiment.yaml")
    args = ap.parse_args()

    base = Path(args.profile)
    tf = terraform_outputs()
    for key in ("minio_private_ip", "tsg_private_ip"):
        if not tf.get(key):
            sys.exit(f"terraform output {key} is empty — run `make tf-apply` first")

    # tsg_host is the PRIVATE ip: run_experiment.py reaches the TSG from the
    # Spark host, from inside the VPC, where the public address is not routable.
    generated = (
        f"\n# --- generated by scripts/configure_profile.py, do not commit ---\n"
        f'endpoint: "http://{tf["minio_private_ip"]}:9000"\n'
        f'minio_ping_host: "{tf["minio_private_ip"]}"\n'
        f'tsg_host: "{tf["tsg_private_ip"]}"\n'
    )
    local = base.with_suffix(".local.yaml")
    local.write_text(base.read_text() + generated)
    print(f"wrote {local}")


if __name__ == "__main__":
    main()
